### ISSUE TITLE
create release with Supervisor v12.8.3 or greater

### ISSUE THREAD

**Issue by 20k-ultra** [balena-os/balena-variscite-mx8#100]
I opened https://github.com/balena-os/meta-balena/pull/2215 to get the change upstream but creating this issue to attach to the support ticket and track here.

**Comment by 20k-ultra** [comment]
Let me know if there is a better repo for Variscite DART-MX8M Mini NRT btw.

**Comment by acostach** [comment]
thanks @20k-ultra. indeed, this is the correct repository (has the imx8mm-var-dart-nrt.coffee machine in it)

**Comment by acostach** [comment]
v2.80.5+rev1 includes supervisor v12.8.7 and is now available in production
