### ISSUE TITLE
Kernel driver for FT232 serial-usb adapter is missing

### ISSUE THREAD

**Issue by spanceac** [balena-os/balena-variscite-mx8#11]
root@13cc52a:~# zcat  /proc/config.gz |grep -i ftd 
\# CONFIG_USB_SERIAL_FTDI_SIO is not set

**Comment by acostach** [comment]
This was most likely raised for a different board. However, it has been fixed in meta-balena since v2.41.1 with PR https://github.com/balena-os/meta-balena/pull/1642) and currently Variscite MX8 includes it, being in production at 2.44.0.
