### ISSUE TITLE
balenad command found

### ISSUE THREAD

**Issue by Robokishan** [balena-os/balena-variscite-mx8#32]
I am trying to compile it as it is shown after an hours of compiling and at 99% when it was about to finish this error came

| Loaded image ID: sha256:81767ce2ff14f22733c312e889266da3a42948a1ce2520d64aeca4ad1d2f5c83
| + SYSROOT=/mnt/sysroot/inactive
| + pid=7
| + sleep 5
| + balenad -s= --data-root=/mnt/sysroot/inactive/balena -H unix:///var/run/balena-host.sock
| /usr/bin/create: line 7: balenad: command not found
| + hostapp-update -f /input -n
| /usr/bin/create: line 11: hostapp-update: command not found
| Deleted: sha256:81767ce2ff14f22733c312e889266da3a42948a1ce2520d64aeca4ad1d2f5c83
| Deleted: sha256:93ed126dc8765b5b97f250c92778213cb9148f980cf9c71dfabd63e3d0fb91f5
| Deleted: sha256:381e292e56f122b744c1d8c1edb5a29f3bd3cb2d294b8f3a08d677869d6ebbe5
| WARNING: exit code 127 from a shell command.

do i have to install balenad and hostapp-update in my computer ?

**Comment by floion** [comment]
Hi, can you paste the exact commands you used?
Also, what is your development machine OS?

**Comment by Robokishan** [comment]
bitbake resin-image

Do i have to install balenad on my host pc ?

**Comment by acostach** [comment]
@Robokishan can you try using barys:

`balena-yocto-scripts/build/barys -b new_build_directory -m imx8mm-var-dart -d `

if you want to build the plain imx8m, you will use `-m imx8m-var-dart`

**Comment by Robokishan** [comment]
yes i am doing only executing that command. but it was giving same error so i tried the command which was printed by barys script both are giving me same error

it seems like error in coming from file image_types_resin.bbclass when it is trying to load image 
mkfs-hostapp-ext4-image.tar. i even tried manually loading this image file but no success there is not balenad in that container that's why it is giving me error

i look at the dockerfile also there is no command which is trying to install balenad in the container
is there any specific command do i have to run before compiling ?

error in coming from this command
`mkfs.hostapp-ext4 -t "${TMPDIR}" -s "${STAGING_DIR_NATIVE}" -i ${RESIN_DOCKER_IMG} -o ${RESIN_HOSTAPP_IMG}`

which is trying to execute create script

**Comment by Robokishan** [comment]
Ok so i tried to debug more and found a script
`meta-balena/meta-balena-common/recipes-containers/mkfs-hostapp-native/files/create`

which has this commands

`balenad -s=@BALENA_STORAGE@ --data-root="$SYSROOT/balena" -H unix:///var/run/balena-host.sock &
pid=$!
sleep 5

hostapp-update -f /input -n`

i commented this command and it is compiling successfully but i am afraid that this command needs to be run right ?
so how do i install balenad ? is there any ppa or some binary which i have to install and not documented ?

**Comment by floion** [comment]
Can you edit the corresponding file in your layer setup, https://github.com/balena-os/balena-qemu/blob/master/layers/meta-balena-qemu/conf/samples/local.conf.sample#L71 and change there `docker` with `balena` ?

**Comment by Robokishan** [comment]
Just for reference I am using the development branch

I will try it and update you

**Comment by floion** [comment]
Why use the development branch? Please use the `master` branch

**Comment by Robokishan** [comment]
Yes sorry my bad i recheck it is master branch

**Comment by Robokishan** [comment]
@floion  Hey i tried to add balena in local.conf.sample but it is still showing me same error.

Is there any significance for this command ?

**Comment by floion** [comment]
@Robokishan after you did the changes did you do a fresh build? Or you continued with the existing build directory? I think that if you did not wipe the existing build directory then that change was not taken into account and that's why you got the same error.
That command is used for creating the host OS update artifacts that are used when updating the underlying host operating system.

**Comment by Robokishan** [comment]
How can i do fresh build ? 
and also for curiosity i flashed built image on to sdcard just to see if all things go well or not but i found out that the resin-rootA partition is totally empty except the resin-boot partition all the partitions are emtpy 
is it normal ?

**Comment by floion** [comment]
1 - You can create a fresh build dir like Alex said above:
> balena-yocto-scripts/build/barys -b some_new_build_directory -m imx8mm-var-dart -d

2 - Yes, that would happen if you commented out that line.

**Comment by Robokishan** [comment]
Ok so am deleting everything and reinitiating build thanks for the knowledge.

FYI: I am doing all these thing in docker container . and i am looking the file

image_types_resin.bbclass
and there is a command which runs the docker container since i am already inside the container and yes i have already mount the docker.sock. so it became the docker in docker.
but may be that's why i am having the issue since it is not correctly mounting the system

**Comment by floion** [comment]
@Robokishan did you try to run it natively too? Ubuntu 16.04 was supported by Poky iirc so it should work fine

**Comment by Robokishan** [comment]
No My host os was ubuntu 18 and it has very difficult relationship with yocto. So i do all my yocto builts inside ubuntu 16 docker image.

**Comment by Robokishan** [comment]
Ok thanks for the help i did run it on the native os which is ubuntu 16.04 and it ran successfully but on the board i am having an issue 

```
[    4.318623] EXT4-fs: Warning: mounting with data=journal disables delayed allocation and O_DIRECT support!
[    4.333685] EXT4-fs (mmcblk0p2): Mount option "data=journal" incompatible with ext2
[    4.348001] EXT4-fs (mmcblk0p2): INFO: recovery required on readonly filesystem
[    4.355523] EXT4-fs (mmcblk0p2): write access will be enabled during recovery
[    4.417091] EXT4-fs (mmcblk0p2): recovery complete
[    4.662645] EXT4-fs (mmcblk0p2): mounted filesystem with journalled data mode. Opts: data=journal
[    4.671883] VFS: Mounted root (ext4 filesystem) readonly on device 179:2.
[    4.691471] devtmpfs: mounted
[    4.701501] Freeing unused kernel memory: 1024K
1970/01/01 00:00:05 could not get mounts:open /proc/self/mountinfo: no such file or directory
[    5.183983] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000100
[    5.183983] 
[    5.193233] ---[ end Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000100
[    5.193233] 
```

Something is wrong with /proce/self/mountinfo 
PS: I Have edited nothing and just run the command balena-yocto-scripts/build/barys and for the refrence i have install the ubuntu 16.04 fresh and compilation gone very smoothly successfully but the board have an error

**Comment by acostach** [comment]
@Robokishan  for which board did you do the build? Can you please post the full barys line? and also the output of git log?

**Comment by Robokishan** [comment]
this is balena-variscite-mx8 repo so i am compiling for variscite-mx8 

git log : 
```
commit 6a97b126c848919cde3187d505e5641820e1d5cc (HEAD -> master, tag: v2.48.0+rev3, origin/master, origin/HEAD)
Author: Balena CI <34882892+balena-ci@users.noreply.github.com>
Date:   Tue May 12 17:43:44 2020 +0300

    v2.48.0+rev3

commit dadeb5302ed19484147bb23e089e57c18d54e87f
Merge: 92a736e 19ff5b5
Author: Alexandru Costache <alexandru@balena.io>
Date:   Tue May 12 16:18:20 2020 +0300

    Merge pull request #30 from balena-os/set_private_field_in_coffee_files
    
    .coffee: Set private to false for the public device types
```

command : ./balena-yocto-scripts/build/barys

**Comment by Robokishan** [comment]
Ok i figured out it was something problem with the board i tried it on another board and it is working thanks.
