### ISSUE TITLE
Update to a recent BalenaOS version (>2.60) to take advantage of time sync improvements

### ISSUE THREAD

**Issue by alexgg** [balena-os/balena-variscite-mx8#73]
For context https://jel.ly.fish/69617eec-b1b0-460c-b23d-eb9915656b57

**Comment by acostach** [comment]
This is requested for the default imx8m-var-dart

**Comment by acostach** [comment]
imx8mm-var-dart now available in production at 2.71.3+rev1

**Comment by acostach** [comment]
Will still need image for imx8m-var-dart

**Comment by acostach** [comment]
imx8m-var-dart is now available in production at 2.73.1+rev1
