### ISSUE TITLE
Add support for LP55231 driver

### ISSUE THREAD

**Issue by danthegoodman1** [balena-os/balena-variscite-mx8#83]
A customer is asking about adding in https://www.ti.com/tool/LP5523SW-LINUX

Specifically: https://www.kernel.org/doc/html/latest/leds/leds-lp55xx.html

See: https://jel.ly.fish/df1d8f39-7d48-4421-802c-4427bf8d111f

**Comment by acostach** [comment]
OS image delivered at v2.80.5+rev1
