### ISSUE TITLE
Update support for the revision 2.0 of the Variscite MX8M development kit

### ISSUE THREAD

**Issue by alexgg** [balena-os/balena-variscite-mx8#84]
The Variscite DART-MX8M currently supports the 1.0 revision of the dev kit. A new v2.0 has been released that requires a different device tree to be detected and used at boot.

**Comment by acostach** [comment]
Addressed by https://github.com/balena-os/balena-variscite-mx8/pull/92

**Comment by acostach** [comment]
Implemented in v2.80.5+rev2 dashboard release, we don't have the v2.0 hardware, users have been informed and will confirm how it works.
