### ISSUE TITLE
Dunfell release requested for imx8mm-var-dart

### ISSUE THREAD

**Issue by acostach** [balena-os/balena-variscite-mx8#89]
User in the forums needs a Dunfell release with Kernel 5.4.85 for the imx8mm-var-dart.

User tested the upstream Variscite sd-card image with this kernel version and confirmed ttymxc2 + custom MCU issues are not present with this kernel version.

Requested in: https://forums.balena.io/t/uart-failure-after-upgrading-to-2-71-3-rev1-from-2-50-1-rev1-on-variscite-imx8m/275528

**Comment by kenna-smith** [comment]
This issue has attached support thread: https://forums.balena.io/t/support-for-hardware-v2-0-of-variscite-var-stk-dt8m-mini-lo-or-var-dvk-dt8m-mini-lo-based-on-dart-mx8m-mini-aka-how-to-patch-balenaos-with-a-newer-dtb-file/309721

**Comment by acostach** [comment]
Addressed by https://github.com/balena-os/balena-variscite-mx8/pull/92

**Comment by acostach** [comment]
Implemented in https://github.com/balena-os/balena-variscite-mx8/pull/102 and available in dashboard image v2.80.5+rev2
